
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author io
 */
public class IuPpal extends javax.swing.JFrame {

    /**
     * Creates new form IuPpal
     */
    public IuPpal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        flcUbicacion = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstResultado = new javax.swing.JList();
        tpnResultados = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtA = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtB = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtUnion = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtInterseccion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1021, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lstResultado);

        txtA.setColumns(20);
        txtA.setRows(5);
        jScrollPane2.setViewportView(txtA);

        tpnResultados.addTab("Grupo A", jScrollPane2);

        txtB.setColumns(20);
        txtB.setRows(5);
        jScrollPane3.setViewportView(txtB);

        tpnResultados.addTab("Grupo B", jScrollPane3);

        txtUnion.setColumns(20);
        txtUnion.setRows(5);
        jScrollPane4.setViewportView(txtUnion);

        tpnResultados.addTab("Unión", jScrollPane4);

        txtInterseccion.setColumns(20);
        txtInterseccion.setRows(5);
        jScrollPane5.setViewportView(txtInterseccion);

        tpnResultados.addTab("Intersección", jScrollPane5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpnResultados)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIniciar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        Modelos c = new Modelos();
        flcUbicacion.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int seleccion = flcUbicacion.showSaveDialog(this);
        
        if (seleccion == flcUbicacion.APPROVE_OPTION) {
            File fichero = flcUbicacion.getSelectedFile();
            String ruta = fichero.getPath() + "/";
            
            boolean modA = c.crearModeloA(ruta + "modelo A.rdf");
            boolean modB = c.crearModeloB(ruta + "modelo B.rdf");
            boolean modUnion = c.crearUnion(ruta + "modelo A.rdf", ruta + "modelo B.rdf", ruta + "unionModelos.rdf");
            boolean modInterseccion = c.crearInterseccion(ruta + "modelo A.rdf", ruta + "modelo B.rdf", ruta + "interseccionModelos.rdf");

            Object datos[]=new Object[8];
            int[] iconos = new int[8];

            datos[0] ="Creando modelo A";
            iconos[0] = RenderLista._LOAD;
            if (modA) {
                datos[1] ="El modelo A fue creado correctamente.";
                iconos[1] = RenderLista._Ok;
                cargarArchivo(ruta + "modelo A.rdf", txtA);
            } else {
                datos[1] ="Error al crear el modelo A";
                iconos[1] = RenderLista._KO;
            }

            datos[2] ="Creando modelo B";
            iconos[2] = RenderLista._LOAD;
            if (modB) {
                datos[3] ="El modelo B fue creado correctamente.";
                iconos[3] = RenderLista._Ok;
                cargarArchivo(ruta + "modelo B.rdf", txtB);
            } else {
                datos[3] ="Error al crear el modelo B";
                iconos[3] = RenderLista._KO;
            }        

            datos[4] ="Creando Unión de modelos";
            iconos[4] = RenderLista._LOAD;
            if (modUnion) {
                datos[5] ="La Unión de modelos fue creada correctamente.";
                iconos[5] = RenderLista._Ok;
                cargarArchivo(ruta + "unionModelos.rdf", txtUnion);
            } else {
                datos[5] ="Error al crear la Unión de modelos";
                iconos[5] = RenderLista._KO;
            }   

            datos[6] ="Creando Intersección";
            iconos[6] = RenderLista._LOAD;
            if (modInterseccion) {
                datos[7] ="La Intersección de modelos fue creada correctamente.";
                iconos[7] = RenderLista._Ok;
                cargarArchivo(ruta + "interseccionModelos.rdf", txtInterseccion);
            } else {
                datos[7] ="Error al crear la Intersección de modelos";
                iconos[7] = RenderLista._KO;
            }   

            lstResultado.setListData(datos);
            RenderLista rl = new RenderLista(iconos);
            lstResultado.setCellRenderer(rl);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IuPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IuPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JFileChooser flcUbicacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList lstResultado;
    private javax.swing.JTabbedPane tpnResultados;
    private javax.swing.JTextArea txtA;
    private javax.swing.JTextArea txtB;
    private javax.swing.JTextArea txtInterseccion;
    private javax.swing.JTextArea txtUnion;
    // End of variables declaration//GEN-END:variables

    private void cargarArchivo(String ruta, JTextArea txt) {
        String contenido = "";
        
        // Apertura del fichero y creacion de BufferedReader para poder
        // hacer una lectura comoda (disponer del metodo readLine()).
        File archivo = null;
        FileReader fr = null;
        BufferedReader br = null;
        
        try {
            archivo = new File (ruta);
            fr = new FileReader (archivo);
            br = new BufferedReader(fr);

            // Lectura del fichero
            String linea;
            while((linea=br.readLine())!=null) {
                contenido += linea + "\n";
                txt.setText(contenido);
            }
        } catch(Exception e){
           e.printStackTrace();
        } finally{
            // En el finally cerramos el fichero, para asegurarnos
            // que se cierra tanto si todo va bien como si salta 
            // una excepcion.
            try{                    
               if( null != fr ){   
                  fr.close();     
               }                  
            }catch (Exception e2){ 
               e2.printStackTrace();
            }
        }
    }
}
